server:
  port: ${SERVER_PORT:18080}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:member-service}
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:13306/member?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:P@ssw0rd$}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${JPA_HIBERNATE_FORMAT_SQL:true}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: ${JWT_SECRET:8O2HQ13etL2BWZvYOiWsJ5uWFoLi6NBUG8divYVoCgtHVvlk3dqRksMl16toztDUeBTSIuOOPvHIrYq11G2BwQ==}
  expiration-time: ${JWT_EXPIRATION_TIME:36000}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME:360000}

# Logging
logging:
  level:
    root: INFO
    com.subride.member.infra.in: DEBUG
    com.subride.member.infra.out: DEBUG

